// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0-devel
// 	protoc        v4.23.4
// source: mt_serialnumber.proto

package masterthesis

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CachedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID     int64  `protobuf:"varint,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	SerialNumber int64  `protobuf:"varint,2,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	LogIdx       uint64 `protobuf:"varint,3,opt,name=logIdx,proto3" json:"logIdx,omitempty"`
	Applied      bool   `protobuf:"varint,4,opt,name=applied,proto3" json:"applied,omitempty"`
	Response     []byte `protobuf:"bytes,5,opt,name=Response,proto3,oneof" json:"Response,omitempty"`
}

func (x *CachedResponse) Reset() {
	*x = CachedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt_serialnumber_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CachedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedResponse) ProtoMessage() {}

func (x *CachedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mt_serialnumber_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedResponse.ProtoReflect.Descriptor instead.
func (*CachedResponse) Descriptor() ([]byte, []int) {
	return file_mt_serialnumber_proto_rawDescGZIP(), []int{0}
}

func (x *CachedResponse) GetClientID() int64 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *CachedResponse) GetSerialNumber() int64 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *CachedResponse) GetLogIdx() uint64 {
	if x != nil {
		return x.LogIdx
	}
	return 0
}

func (x *CachedResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *CachedResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_mt_serialnumber_proto protoreflect.FileDescriptor

var file_mt_serialnumber_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x74,
	0x68, 0x65, 0x73, 0x69, 0x73, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x01,
	0x0a, 0x0e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x65, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x24, 0xc8, 0xe1, 0x1e, 0x00, 0xd0, 0xe1, 0x1e, 0x00, 0xc8, 0xe2, 0x1e, 0x01, 0xd0, 0xe2,
	0x1e, 0x01, 0xe0, 0xe2, 0x1e, 0x01, 0x5a, 0x0e, 0x2e, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x74, 0x68, 0x65, 0x73, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mt_serialnumber_proto_rawDescOnce sync.Once
	file_mt_serialnumber_proto_rawDescData = file_mt_serialnumber_proto_rawDesc
)

func file_mt_serialnumber_proto_rawDescGZIP() []byte {
	file_mt_serialnumber_proto_rawDescOnce.Do(func() {
		file_mt_serialnumber_proto_rawDescData = protoimpl.X.CompressGZIP(file_mt_serialnumber_proto_rawDescData)
	})
	return file_mt_serialnumber_proto_rawDescData
}

var file_mt_serialnumber_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mt_serialnumber_proto_goTypes = []interface{}{
	(*CachedResponse)(nil), // 0: masterthesis.CachedResponse
}
var file_mt_serialnumber_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mt_serialnumber_proto_init() }
func file_mt_serialnumber_proto_init() {
	if File_mt_serialnumber_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mt_serialnumber_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CachedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mt_serialnumber_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mt_serialnumber_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mt_serialnumber_proto_goTypes,
		DependencyIndexes: file_mt_serialnumber_proto_depIdxs,
		MessageInfos:      file_mt_serialnumber_proto_msgTypes,
	}.Build()
	File_mt_serialnumber_proto = out.File
	file_mt_serialnumber_proto_rawDesc = nil
	file_mt_serialnumber_proto_goTypes = nil
	file_mt_serialnumber_proto_depIdxs = nil
}
