---
name: grpcProxy-tests
on: [push, pull_request]
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          - linux-amd64-grpcproxy-integration
          - linux-amd64-grpcproxy-e2e
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          set -euo pipefail

          echo "${TARGET}"
          case "${TARGET}" in
            linux-amd64-grpcproxy-integration)
              GOOS=linux GOARCH=amd64 CPU=4 RACE=true make test-grpcproxy-integration
              ;;
            linux-amd64-grpcproxy-e2e)
              GOOS=linux GOARCH=amd64 CPU=4 RACE=true make test-grpcproxy-e2e
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac
